from alpine:3.8

run apk add \
      --no-cache \
      g++ \
      make \
      gawk \
      gzip \
      bzip2 \
      tar \
      xz \
      lzip \
      coreutils \
      ninja \
      cmake

copy build-gcc-8.2.0.sh /tmp/
